apiVersion: v1
kind: Service
metadata:
  name: food-db-server
  labels:
    component: food-db-server
spec:
  type: NodePort
  selector:
    component: food-db-server
  ports:
    - name: mongonative
      port: 27017
      targetPort: mongonative
