apiVersion: v1
kind: Service
metadata:
  name: food-db-server
  labels:
    component: food-db-server
spec:
  clusterIP: None
  selector:
    component: food-db-server
  ports:
    - port: 27017
      name: mongoport
      targetPort: 27017
