apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: couchbase
  labels:
    component: couchbase
spec:
  replicas: 1
  selector:
    matchLabels:
      component: couchbase
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: couchbase
      labels:
        component: couchbase
    spec:
      containers:
      - name: couchbase
        image: couchbase:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8091
          - containerPort: 8092
          - containerPort: 8093
          - containerPort: 8094
          - containerPort: 11210
