apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: food-db-server
  labels:
    component: food-db-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: food-db-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: food-db-server
      labels:
        component: food-db-server
    spec:
      containers:
      - name: food-db-server
        image: mongo:4
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-credentials
                key: initdb_root_username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-credentials
                key: initdb_root_passwd
        ports:
          - containerPort: 27017
            name: mongonative
