apiVersion: batch/v1
kind: Job
metadata:
  name: food-db-test
spec:
  template:
    metadata:
      name: food-db-test
    spec:
      initContainers:
      - name: wait-for-food-db
        image: masterofless/go-food/wait-for-food-db:master.383
      containers:
      - name: food-db-test
        image: masterofless/go-food/food-db-test:master.383
      restartPolicy: OnFailure
